### PR TITLE
Update max NUMA check from 16 to 20

### PR DESCRIPTION
**Pull request by vrragosta**
Update NUMA check from 16 to 20.

Deleted redundant NUMA check test.

### CODE REVIEW

**Review by vince-weka — COMMENTED** [review]
Should probably check weka version, as if this is run on an existing cluster, it might not be at 4.2.11...

**Comment by vrragosta** [comment]
> Should probably check weka version, as if this is run on an existing cluster, it might not be at 4.2.11...

Updated with most recent commit.

**Review by jackchallen — APPROVED** [review]
Yep, version detection looks sane

**Comment by jackchallen** [comment]
Resolving merge conflicts

**Pull request merged**
